name: Deploy Flyway Migrations

on:
  push:
    branches: [ "main" ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyway
        run: |
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.17.2/flyway-commandline-10.17.2-linux-x64.tar.gz -o flyway.tar.gz
          tar -xzf flyway.tar.gz
          sudo ln -s $PWD/flyway-10.17.2/flyway /usr/local/bin/flyway
          flyway -v

      - name: Run Flyway Migrate
        env:
          FLYWAY_URL: ${{ secrets.FLYWAY_URL }}
          FLYWAY_USER: ${{ secrets.FLYWAY_USER }}
          FLYWAY_PASSWORD: ${{ secrets.FLYWAY_PASSWORD }}
        run: |
          flyway -configFiles=flyway.conf migrate